In [ ]:
import numpy as np
import matplotlib as plt
import pandas as pd
from flight_project_functions import *
from datetime import datetime

df = pd.read_csv('itineraries.csv')
print(len(df))
df.head(10)
df = df.dropna()
print(len(df))
print(df.columns)
data_types(df)
df.head(10)

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (8,9,10) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

78318
73069
Index(['legId', 'searchDate', 'flightDate', 'startingAirport',
       'destinationAirport', 'fareBasisCode', 'travelDuration', 'elapsedDays',
       'isBasicEconomy', 'isRefundable', 'isNonStop', 'baseFare', 'totalFare',
       'seatsRemaining', 'totalTravelDistance',
       'segmentsDepartureTimeEpochSeconds', 'segmentsDepartureTimeRaw',
       'segmentsArrivalTimeEpochSeconds', 'segmentsArrivalTimeRaw',
       'segmentsArrivalAirportCode', 'segmentsDepartureAirportCode',
       'segmentsAirlineName', 'segmentsAirlineCode',
       'segmentsEquipmentDescription', 'segmentsDurationInSeconds',
       'segmentsDistance', 'segmentsCabinCode'],
      dtype='object')
legId type is {<class 'str'>}
searchDate type is {<class 'str'>}
flightDate type is {<class 'str'>}
startingAirport type is {<class 'str'>}
destinationAirport type is {<class 'str'>}
fareBasisCode type is {<class 'str'>}
travelDuration type is {<class 'str'>}
elapsedDays type is {<class 'float'>}
isBasicEconomy type is {<class 'bool'>}
isRefundable type is {<class 'bool'>}
isNonStop type is {<class 'bool'>}
baseFare type is {<class 'float'>}
totalFare type is {<class 'float'>}
seatsRemaining type is {<class 'float'>}
totalTravelDistance type is {<class 'float'>}
segmentsDepartureTimeEpochSeconds type is {<class 'str'>}
segmentsDepartureTimeRaw type is {<class 'str'>}
segmentsArrivalTimeEpochSeconds type is {<class 'str'>}
segmentsArrivalTimeRaw type is {<class 'str'>}
segmentsArrivalAirportCode type is {<class 'str'>}
segmentsDepartureAirportCode type is {<class 'str'>}
segmentsAirlineName type is {<class 'str'>}
segmentsAirlineCode type is {<class 'str'>}
segmentsEquipmentDescription type is {<class 'str'>}
segmentsDurationInSeconds type is {<class 'str'>}
segmentsDistance type is {<class 'str'>}
segmentsCabinCode type is {<class 'str'>}

,legId,searchDate,flightDate,startingAirport,destinationAirport,fareBasisCode,travelDuration,elapsedDays,isBasicEconomy,isRefundable,...,segmentsArrivalTimeEpochSeconds,segmentsArrivalTimeRaw,segmentsArrivalAirportCode,segmentsDepartureAirportCode,segmentsAirlineName,segmentsAirlineCode,segmentsEquipmentDescription,segmentsDurationInSeconds,segmentsDistance,segmentsCabinCode
0,9ca0e81111c683bec1012473feefd28f,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H29M,0.0,False,False,...,1650223560,2022-04-17T15:26:00.000-04:00,BOS,ATL,Delta,DL,Airbus A321,8940,947,coach
1,98685953630e772a098941b71906592b,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H30M,0.0,False,False,...,1650200400,2022-04-17T09:00:00.000-04:00,BOS,ATL,Delta,DL,Airbus A321,9000,947,coach
2,98d90cbc32bfbb05c2fc32897c7c1087,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H30M,0.0,False,False,...,1650218700,2022-04-17T14:05:00.000-04:00,BOS,ATL,Delta,DL,Boeing 757-200,9000,947,coach
3,969a269d38eae583f455486fa90877b4,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H32M,0.0,False,False,...,1650227460,2022-04-17T16:31:00.000-04:00,BOS,ATL,Delta,DL,Airbus A321,9120,947,coach
4,980370cf27c89b40d2833a1d5afc9751,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H34M,0.0,False,False,...,1650213180,2022-04-17T12:33:00.000-04:00,BOS,ATL,Delta,DL,Airbus A321,9240,947,coach
6,9335fae376c38bb61263281779f469ec,2022-04-16,2022-04-17,ATL,BOS,V0AJZNN1,PT4H12M,0.0,False,False,...,1650203400||1650213120,2022-04-17T09:50:00.000-04:00||2022-04-17T12:3...,CLT||BOS,ATL||CLT,American Airlines||American Airlines,AA||AA,Airbus A320||Airbus A320,5400||7500,228||728,coach||coach
7,3904bf87f2d1daf334f1ae7e3b876028,2022-04-16,2022-04-17,ATL,BOS,V0AJZNN1,PT5H18M,0.0,False,False,...,1650203400||1650217080,2022-04-17T09:50:00.000-04:00||2022-04-17T13:3...,CLT||BOS,ATL||CLT,American Airlines||American Airlines,AA||AA,Airbus A320||Boeing 737-800,5400||8280,228||728,coach||coach
8,d93988734c44a3c075d9efe373352507,2022-04-16,2022-04-17,ATL,BOS,V0AJZNN1,PT5H32M,0.0,False,False,...,1650198060||1650213120,2022-04-17T08:21:00.000-04:00||2022-04-17T12:3...,CLT||BOS,ATL||CLT,American Airlines||American Airlines,AA||AA,Airbus A319||Airbus A320,4860||7500,228||728,coach||coach
9,562e7d5dd6ecbf1509c0c19711dbdca9,2022-04-16,2022-04-17,ATL,BOS,V0AJZNN1,PT6H38M,0.0,False,False,...,1650198060||1650217080,2022-04-17T08:21:00.000-04:00||2022-04-17T13:3...,CLT||BOS,ATL||CLT,American Airlines||American Airlines,AA||AA,Airbus A319||Boeing 737-800,4860||8280,228||728,coach||coach
10,c38a6e4b807d15541e5866676febcbec,2022-04-16,2022-04-17,ATL,BOS,VAA0AKEN,PT4H46M,0.0,False,False,...,1650194280||1650204960,2022-04-17T07:18:00.000-04:00||2022-04-17T10:1...,IAD||BOS,ATL||IAD,United||United,UA||UA,Airbus A319||Boeing 737-800,6480||5940,541||406,coach||coach

In [ ]:
df = df.drop(columns = 
['legId','fareBasisCode', 'travelDuration', 'segmentsDistance'], axis = 1)
print(df.isnull().sum())
print(df.nunique()) 
df.head(10)

searchDate                           0
flightDate                           0
startingAirport                      0
destinationAirport                   0
elapsedDays                          0
isBasicEconomy                       0
isRefundable                         0
isNonStop                            0
baseFare                             0
totalFare                            0
seatsRemaining                       0
totalTravelDistance                  0
segmentsDepartureTimeEpochSeconds    0
segmentsDepartureTimeRaw             0
segmentsArrivalTimeEpochSeconds      0
segmentsArrivalTimeRaw               0
segmentsArrivalAirportCode           0
segmentsDepartureAirportCode         0
segmentsAirlineName                  0
segmentsAirlineCode                  0
segmentsEquipmentDescription         0
segmentsDurationInSeconds            0
segmentsCabinCode                    0
dtype: int64
searchDate                               1
flightDate                              10
startingAirport                         16
destinationAirport                      16
elapsedDays                              2
isBasicEconomy                           2
isRefundable                             2
isNonStop                                2
baseFare                              2588
totalFare                             4828
seatsRemaining                          10
totalTravelDistance                   1577
segmentsDepartureTimeEpochSeconds    54212
segmentsDepartureTimeRaw             58656
segmentsArrivalTimeEpochSeconds      60207
segmentsArrivalTimeRaw               64069
segmentsArrivalAirportCode            1590
segmentsDepartureAirportCode          1550
segmentsAirlineName                     78
segmentsAirlineCode                     78
segmentsEquipmentDescription          1923
segmentsDurationInSeconds            15572
segmentsCabinCode                       32
dtype: int64

,searchDate,flightDate,startingAirport,destinationAirport,elapsedDays,isBasicEconomy,isRefundable,isNonStop,baseFare,totalFare,...,segmentsDepartureTimeRaw,segmentsArrivalTimeEpochSeconds,segmentsArrivalTimeRaw,segmentsArrivalAirportCode,segmentsDepartureAirportCode,segmentsAirlineName,segmentsAirlineCode,segmentsEquipmentDescription,segmentsDurationInSeconds,segmentsCabinCode
0,2022-04-16,2022-04-17,ATL,BOS,0.0,False,False,True,217.67,248.6,...,2022-04-17T12:57:00.000-04:00,1650223560,2022-04-17T15:26:00.000-04:00,BOS,ATL,Delta,DL,Airbus A321,8940,coach
1,2022-04-16,2022-04-17,ATL,BOS,0.0,False,False,True,217.67,248.6,...,2022-04-17T06:30:00.000-04:00,1650200400,2022-04-17T09:00:00.000-04:00,BOS,ATL,Delta,DL,Airbus A321,9000,coach
2,2022-04-16,2022-04-17,ATL,BOS,0.0,False,False,True,217.67,248.6,...,2022-04-17T11:35:00.000-04:00,1650218700,2022-04-17T14:05:00.000-04:00,BOS,ATL,Delta,DL,Boeing 757-200,9000,coach
3,2022-04-16,2022-04-17,ATL,BOS,0.0,False,False,True,217.67,248.6,...,2022-04-17T13:59:00.000-04:00,1650227460,2022-04-17T16:31:00.000-04:00,BOS,ATL,Delta,DL,Airbus A321,9120,coach
4,2022-04-16,2022-04-17,ATL,BOS,0.0,False,False,True,217.67,248.6,...,2022-04-17T09:59:00.000-04:00,1650213180,2022-04-17T12:33:00.000-04:00,BOS,ATL,Delta,DL,Airbus A321,9240,coach
6,2022-04-16,2022-04-17,ATL,BOS,0.0,False,False,False,213.02,251.1,...,2022-04-17T08:20:00.000-04:00||2022-04-17T10:2...,1650203400||1650213120,2022-04-17T09:50:00.000-04:00||2022-04-17T12:3...,CLT||BOS,ATL||CLT,American Airlines||American Airlines,AA||AA,Airbus A320||Airbus A320,5400||7500,coach||coach
7,2022-04-16,2022-04-17,ATL,BOS,0.0,False,False,False,213.02,251.1,...,2022-04-17T08:20:00.000-04:00||2022-04-17T11:2...,1650203400||1650217080,2022-04-17T09:50:00.000-04:00||2022-04-17T13:3...,CLT||BOS,ATL||CLT,American Airlines||American Airlines,AA||AA,Airbus A320||Boeing 737-800,5400||8280,coach||coach
8,2022-04-16,2022-04-17,ATL,BOS,0.0,False,False,False,213.02,251.1,...,2022-04-17T07:00:00.000-04:00||2022-04-17T10:2...,1650198060||1650213120,2022-04-17T08:21:00.000-04:00||2022-04-17T12:3...,CLT||BOS,ATL||CLT,American Airlines||American Airlines,AA||AA,Airbus A319||Airbus A320,4860||7500,coach||coach
9,2022-04-16,2022-04-17,ATL,BOS,0.0,False,False,False,213.02,251.1,...,2022-04-17T07:00:00.000-04:00||2022-04-17T11:2...,1650198060||1650217080,2022-04-17T08:21:00.000-04:00||2022-04-17T13:3...,CLT||BOS,ATL||CLT,American Airlines||American Airlines,AA||AA,Airbus A319||Boeing 737-800,4860||8280,coach||coach
10,2022-04-16,2022-04-17,ATL,BOS,0.0,False,False,False,213.02,252.6,...,2022-04-17T05:30:00.000-04:00||2022-04-17T08:3...,1650194280||1650204960,2022-04-17T07:18:00.000-04:00||2022-04-17T10:1...,IAD||BOS,ATL||IAD,United||United,UA||UA,Airbus A319||Boeing 737-800,6480||5940,coach||coach

df['segmentsDurationInSeconds'] = df['segmentsArrivalTimeEpochSeconds'] - df['segmentsDepartureTimeEpochSeconds'] so I will drop segmentsArrivalTimeEpochSeconds and segmentsDepartureTimeEpochSeconds

In [ ]:
df = df.drop(columns =
['segmentsArrivalTimeEpochSeconds','segmentsDepartureTimeEpochSeconds'], axis = 1)
df['segmentsDurationInSeconds'] = df['segmentsDurationInSeconds'].apply(total)
df['searchDate'] = df['searchDate'].astype('datetime64[ns]')
df['flightDate'] = df['flightDate'].astype('datetime64[ns]')
df['daysUntilFlight'] = df['flightDate'] - df['searchDate']
df = df.drop(columns = ['flightDate','searchDate'], axis = 1)
df['daysUntilFlight'] = df['daysUntilFlight'].astype('str')
df['daysUntilFlight'] = df['daysUntilFlight'].apply(lambda x: int(x[0]))
df= df[df['seatsRemaining'] > 0]
df['segmentsCabinCode'] = df['segmentsCabinCode'].apply(total)
df['numberOfChanges'] = df['segmentsCabinCode'] - 1
df = df.drop(columns =
['segmentsCabinCode', 'segmentsAirlineCode'], axis = 1)
df[(df['isNonStop'] == True) & (df['numberOfChanges'] == 0)]
print(df.columns)
print(len(df))
df.head(10)

KeyError: ignored